### PR TITLE
SimpleVote - 7 more tests (passing) + bugfix for cancelVote

### PR DESCRIPTION
**Pull request by assafmo**

### CODE REVIEW

**Comment by jellegerbrandy** [comment]
Really good job, assafmo! Many thanks. Good call on the bug as well.

I'll merge it when I get the time (or perhaps @leviadam  can). 

Given that you have added the _voter arg to cancelVote, we probably also want the "if not specifed, _voter = msg.sender" stanza that is also in vote():

```
        if (msg.sender != proposal.owner) {
            _voter = msg.sender;
        }
```

**Comment by assafmo** [comment]
@jellegerbrandy you are right. I still due think that the owner shouldn't be allow to vote for other parties as we discussed in #66.

**Comment by assafmo** [comment]
@jellegerbrandy I added your remark to the PR.
Those sort of scenarios shoud be **heavily** test.

**Comment by assafmo** [comment]
Added 2 more tests.

**Comment by leviadam** [comment]
Tests are failing. Linting problem.

**Comment by assafmo** [comment]
mmm... What linter should I be using?

**Comment by leviadam** [comment]
eslint.
And you should run `yarn lint` before committing.

**Pull request merged**
