### PR TITLE
Update npm dependencies

### LINKED ISSUE #194: Upgrade truffle  to v4.0.4
https://github.com/trufflesuite/truffle/releases/tag/v4.0.4

### PR DESCRIPTION
**Pull request by Alonski**
There are also other packages that could be updated:
Fixes #194 

 babel-eslint             ^7.2.3  →          ^8.1.2
 bignumber.js             ^4.1.0  →          ^5.0.0
 eslint-config-standard  ^10.2.1  →  ^11.0.0-beta.0
 pm2                      ^1.1.3  →          ^2.9.1

 ethers                      ^2.1.2  →       ^2.1.3
 babel-polyfill             ^6.23.0  →      ^6.26.0
 babel-register             ^6.24.1  →      ^6.26.0
 eslint                     ^4.10.0  →      ^4.14.0
 eslint-plugin-import        ^2.7.0  →       ^2.8.0
 eslint-plugin-node          ^5.1.1  →       ^5.2.1
 eslint-plugin-promise       ^3.5.0  →       ^3.6.0
 eslint-plugin-react         ^7.4.0  →       ^7.5.1
 pug                    ^2.0.0-rc.1  →  ^2.0.0-rc.4
 solc                       ^0.4.18  →      ^0.4.19
 solium                      ^1.0.9  →       ^1.1.0
 zeppelin-solidity           ^1.4.0  →       ^1.5.0

### CODE REVIEW

**Comment by orenyodfat** [comment]
Thanks @Alonski .
Lets try to update also the packages above.

**Comment by Alonski** [comment]
Apparently Zeppelin made a breaking change to where StandardTokenMock.sol is placed.
This wasn't failing locally for me because I didn't nuke my build folder.
Fixing this now

**Comment by orenyodfat** [comment]
As solc version is now up to 0.4.19 ,I guess we should  bump up all solidity files pragma to ^0.4.19 .

**Comment by Alonski** [comment]
Updated Dependencies again.
babel-preset-es2015 seems to be deprecated as stated here: http://babeljs.io/env

**Comment by leviadam** [comment]
Hi @Alonski,

Truffle still does not support 0.4.19. So we stick with 0.4.18 for now.
I think you can remove `babel-preset-es2015`.
But make sure everything works on a clean clone.

**Comment by Alonski** [comment]
@leviadam 
Regarding `babel-preset-es2015`.
I tried changing to `babel-preset-env` but it seems that other libraries still depend on the old library and thus don't work.
Could this be merged in without it?

**Comment by orenyodfat** [comment]
@Alonski I guess you can avoid these merge commits (e.g a0630ad)  using git rebase.
This commits are not needed to review and  appears (if they are not squashed on the merging action ) on the master branch which might cause confusion.
Please squash it and push force your branch again.

**Pull request merged**
