### PR TITLE
Commented-out calls to assert

### PR DESCRIPTION
**Pull request by dkent600**
#112 - calls to `assert` are crashing application code

### CODE REVIEW

**Comment by leviadam** [comment]
Not sure about deleting the `asset` commands.
Is there a reason why it crashes things?

**Comment by dkent600** [comment]
@leviadam It crashes because `assert` doesn't exist outside of the test environment

**Comment by dkent600** [comment]
The alternative is to stub it out when it doesn't exist.  I can do that if you prefer.

**Comment by leviadam** [comment]
No, we can go without asserts in the lib, and have tests.

**Pull request merged**
