### PR TITLE
Fix Slack Link

### PR DESCRIPTION
**Pull request by Alonski**

### CODE REVIEW

**Comment by Alonski** [comment]
BTW, maybe the slack link should link to a service that sends out Slack invitations?
Something like: https://github.com/rauchg/slackin
I can get this setup if I had the resources

**Comment by leviadam** [comment]
I think we have to decide if slack is our main channel. After we decide it might be worth it.
Thanks.

**Comment by Alonski** [comment]
@leviadam Is there a current chat for the project, not necessarily slack?

**Comment by leviadam** [comment]
At the moment we still use slack.
https://daostack.slack.com

**Comment by Alonski** [comment]
@leviadam Is it possible to get an invite so I can see where I can contribute more?

**Pull request merged**
