### PR TITLE
Update npm

### PR DESCRIPTION
**Pull request by orenyodfat**
add .npmignore to add contracts jsons to the npm. see issue #209 
update .gitignore.

### CODE REVIEW

**Comment by orenyodfat** [comment]
This PR just add .npmignore to include the build dir in the npm.
How it related to the dependencies ?

**Comment by dkent600** [comment]
There is no need to add an .npmignore file.  What I've done is simpler and also deals with dependency changes.

**Comment by dkent600** [comment]
BTW, what I've done is safer too.  Instead of specifying what should *not* go in, it specifies what *should* go in.  That is safer, helps prevent unwanted stuff from getting into the package.

**Comment by orenyodfat** [comment]
I added .npmignore inorder to include the build dir which is excluded by .gitignore 
https://docs.npmjs.com/cli/publish#description

**Comment by dkent600** [comment]
I did the same thing by adding it to package.json.

**Comment by orenyodfat** [comment]
I am closing this PR as @dkent600 already done work in this direction.

**Pull request closed without merging**
