### PR TITLE
AbsoluteVote : Properly delete proposal.

### PR DESCRIPTION
**Pull request by orenyodfat**
This PR include the following : 
1. Properly delete proposal .
   By deleting its internal map .see here http://solidity.readthedocs.io/en/develop/types.html#delete
   This address a TODO at AbolusteVote "Sanity checks".
2. Change VoteInfo to return uint[2] (instead of uint[13]) .
    Did I missed something here ?
4. Fix spelling
5. Update solidity code according [Solidity official style guide](   http://solidity.readthedocs.io/en/develop/style-guide.html)

### CODE REVIEW

**Comment by orenyodfat** [comment]
@leviadam this is confusing : 
https://github.com/daostack/daostack/blob/dev/contracts/VotingMachines/AbsoluteVote.sol#L129
https://github.com/daostack/daostack/blob/dev/contracts/VotingMachines/AbsoluteVote.sol#L177
Though vote is uint (unsigned) .I guess that some historical remaining .right ?

**Comment by orenyodfat** [comment]
commit 921e265 : 
1. Remove voteInfo and proposalStatus from vote machine interface.
2. Set votable modifier on the interface function and remove it from internalVote.
3. Make internalVote private (was internal).
4. Add isVotable to vote machine interface.
5. Update tests accordingly.

**Comment by leviadam** [comment]
Hi @orenyodfat, great work.
In the future if you can separate commits of linting and commits of actual changes would be great, so it will be more easy to check changes.

**Comment by orenyodfat** [comment]
@leviadam ok .
It will be great if you could approve the PR before merging it.
I would recommend to add this "Required reviews" option to the github repo so it can be enforced.
https://help.github.com/articles/about-pull-request-reviews/#required-reviews

**Comment by leviadam** [comment]
Agreed.

**Pull request merged**
