### PR TITLE
test-rpc changed to ganache-cli

### PR DESCRIPTION
**Pull request by Alonski**

### CODE REVIEW

**Comment by leviadam** [comment]
Good job.

**Comment by leviadam** [comment]
Note that this PR was to `docs` branch.
You need to PR to master.

**Comment by Alonski** [comment]
Yes I noticed this as well. I'll fix this in master

**Comment by Alonski** [comment]
@leviadam I see that the `docs` branch hasn't been merged into master yet. So there is nothing to fix as the README.md in master right now isn't as updated as this one

**Pull request merged**
